name: CI

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mlugg/setup-zig@v2

      - run: zig fmt . --check
      - run: |
          zig build test
          zig build test -Doptimize=ReleaseSafe
          zig build test -Doptimize=ReleaseFast
          zig build test -Doptimize=ReleaseSmall

  master:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mlugg/setup-zig@v2
        with:
          version: master

      - run: zig build test
